version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file: ./backend/.env
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
      - postgres
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: ./backend/.env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin1:
    image: dpage/pgadmin4
    container_name: pgadmin1
    env_file: ./backend/.env
    ports:
      - "5008:80"
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
